<?php if ($this->isTagalysEnabled()): ?> 
    <?php
        $useLegacyJavaScript = $this->getUseLegacyJavaScript();
        $thisCategory = false;
        try{
            $thisCategory = $this->getCurrentCategory();
        } catch (\Exception $e) { }
    ?>
    <?php if($thisCategory != false): ?>
        <script>
            onTagalysReady(function() {
                try {
                    if (typeof(__tagalysRendered) == 'undefined' || !__tagalysRendered) {
                        Tagalys.Analytics.trackProductListingPageView("<?php echo $thisCategory->getId(); ?>")
                    }
                } catch(error) {
                    console.error(error)
                }
            });
        </script>
    <?php endif; ?>
<?php endif; ?>