<?php
$eventDetails = false;
if($this->isTagalysEnabled()) {
    try{
        $thisCategory = $this->getCurrentCategory();
        if(!$this->isCategoryRenderedByTagalys($thisCategory)) {
            $isTagalysCreated = $this->isTagalysCreated();
            $eventDetails = [
                'pl_type' => $isTagalysCreated ? 'page-tagalys' : 'page-platform',
                'pl_details' => ['page_id' => $thisCategory->getId()],
                'pl_products' => []
            ];
        }
    } catch (\Exception $e) { }
}
?>

<script>
    require(['jquery', 'jquery/ui'], function(jQuery){
        jQuery(document).on('tagalys:ready', function() {
            try {
                if (typeof(__tagalysRendered) == 'undefined' || !__tagalysRendered) {
                    var eventDetails = <?php echo json_encode($eventDetails) ?>;
                    if(eventDetails){
                        Tagalys.UIWidgets.trackEvent('product_list', eventDetails);
                    }
                }
            } catch(error) {
                console.error(error)
            }
        });
    });
</script>
