<?php if ($this->isTagalysEnabled()): ?>
    <?php
        $eventDetails = false;
        try {
            $eventDetails = $this->getEventDetails();
        } catch (\Exception $e) {
            // don't log this as it might happen too often
        }
    ?>
    <?php if ($eventDetails != false): ?>
        <script>
            onTagalysReady(function () {
                try {
                    Tagalys.UIWidgets.trackEvent('product_action', <?php echo json_encode($eventDetails) ?>);
                }
                catch(err) {
                    console.error(err);
                }
            })
        </script>
    <?php endif; ?>
<?php endif; ?>
