<script>
    var onTagalysReady = function(callback) {
        if (window.Tagalys) {
            callback();
            return;
        }
        document.addEventListener("tagalys:ready", function() {
            callback();
        });
    };
</script>

<?php if ($this->isTagalysEnabled()) : ?>
    <?php
        $currency = $this->getCurrentCurrency();
        $apiCredentials = $this->apiCredentials();
        $jsFileUrl = $this->getTagalysJsUrl();
    ?>
    <script src="<?php echo $jsFileUrl ?>" async></script>
    <script>
        try {
            onTagalysReady(function() {
                Tagalys.setConfiguration({
                    api: {
                        serverUrl: '<?php echo $apiCredentials['api_server'] ?>',
                        credentials: {
                            clientCode: "<?php echo $apiCredentials['client_code'] ?>",
                            apiKey: "<?php echo $apiCredentials['public_api_key'] ?>",
                        },
                        storeId: "<?php echo $this->getCurrentStoreId() ?>",
                    },
                    platform: "Magento",
                    locale: "en-US",
                    currency: {
                        displayFormatter: "{{currencyLabel}}{{value}}",
                        code: "<?php echo $currency['id']; ?>",
                        label: "<?php echo $currency['label']; ?>",
                        fractionalDigits: "<?php echo  $currency['fractional_digits']; ?>",
                        forceFractionalDigits: true,
                        exchangeRate: "<?php echo  $currency['exchange_rate']; ?>",
                    },
                    platformVariables: {
                        uenc: "<?php echo $this->getUenc() ?>",
                        formKey: "<?php echo $this->getFormKey() ?>"
                    },
                    analyticsStorageConsentProvided: function() {
                        // return true/false based on user's consent settings
                        return true;
                    },
                    track: true,
                });
            });
        } catch (err) {
            console.error("Error while initializing Tagalys:", err);
        }
    </script>
<?php endif; ?>
