<?php if ($this->isTagalysEnabled()): ?>
    <script>
        require(['jquery', 'jquery/ui', 'tagalys'], function(jQuery){
            try {
                var _tagalysEvent = jQuery.fn.tagalys_analytics.getCookie('__ta_event');
                if (_tagalysEvent != '') {
                    _tagalysEvent = JSON.parse(decodeURIComponent(_tagalysEvent));
                }
                if (_tagalysEvent != '') {
                    var track = true;
                    jQuery.fn.tagalys_analytics.deleteCookie('__ta_event');
                    jQuery(document).on('tagalys:ready', function() {
                        var action = _tagalysEvent[2];
                        if(action == 'buy') {
                            var last_tracked_order_id = jQuery.fn.tagalys_analytics.getCookie('__ta_last_order_id');
                            if (last_tracked_order_id == _tagalysEvent[4]) {
                                track = false;
                            } else {
                                jQuery.fn.tagalys_analytics.setCookie('__ta_last_order_id', _tagalysEvent[4], 24*60*60*1000);
                            }
                        }
                        if (track) {
                            jQuery.ajax({
                                url: "<?php echo $this->getProductDetailsUrl(); ?>",
                                data: { event_json: JSON.stringify(_tagalysEvent) },
                                dataType: 'json',
                                method: 'POST',
                                type: 'POST',
                                global: false,
                                context: _tagalysEvent,
                                success: function(data, textStatus, jqXHR) {
                                    for (var i = 0; i < this[3].length; i++) {
                                        if (this[2] == 'buy') {
                                            jQuery.fn.tagalys_analytics.track_event(this[1], jQuery.extend({ action: this[2], order_id: this[4] }, data[i]));
                                        } else {
                                            jQuery.fn.tagalys_analytics.track_event(this[1], jQuery.extend({ action: this[2] }, data[i]));
                                        }
                                    }
                                }
                            });
                        }
                    });
                }
            }
            catch(err) {
                console.error(err);
            }
            try {
                jQuery(document).on('tagalys:ready', function() {
                    var logged_in_user_id = jQuery.fn.tagalys_analytics.getCookie('__ta_logged_in');
                    if(logged_in_user_id != ""){
                        jQuery.fn.tagalys_analytics.track_user(logged_in_user_id);
                        jQuery.fn.tagalys_analytics.deleteCookie('__ta_logged_in');
                    }
                });
            }
            catch(err) {
                console.error(err);
            }
        });         
    </script>
<?php endif; ?>